### ISSUE TITLE
How to run `hello world` ?

### ISSUE THREAD

**Issue by bergel** [LabWare/ScarletSmallTalk#1]
Hello,

I created a file:
```Smalltalk
Object subclass: #MyApp
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MyApp'!

! MyApp methodsFor: 'public' !
main
	Transcript show: 'Hello world!' ! !
```

How can I compile this file and execute it?
I was expecting to find a `scarlet` executable in a `bin` folder, but this is not the case.

**Comment by mrueger42** [comment]
Scarlet only translates to Javascript, you then need to run it in nodejs or similar.
We haven't really set it up yet to work like an app, for now we were aiming at compilation and using it on mobile.
It is actually an interesting idea to generate a Javascript file that would auto run the main function of an App object/class. 
We are just at early beginnings...

**Comment by johnmci** [comment]
Later today Sebastian and I will take your example class and show how to compile them launch nodejs and then do interactive commands

**Comment by HCHeidbrink** [comment]
you can execute ./scarlet to access the help.
The idea is to either compile .st files, or build a full mobile.js image containing Scarlet and your application code.
We will incorporate your example.
Thank you for your feedback and contribution

**Comment by bergel** [comment]
I tried to run:
```
 ./scarlet compile /Users/alexandrebergel/Desktop/myapp.st 
source: /Users/alexandrebergel/Desktop/myapp.st
/Users/alexandrebergel/Desktop/myapp.st
compile: /Users/alexandrebergel/Desktop/myapp.st
undefined
```

But I could not see the produced javascript file. Oddly enough, if I try to compile the same file a second time, I get the error:
```
➜  ScarletSmallTalk git:(master) ✗ ./scarlet /Users/alexandrebergel/Desktop/myapp.st            
/Users/alexandrebergel/Desktop/myapp.st
undefined:1
Object subclass: #MyApp
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.<anonymous> (/private/tmp/ScarletSmallTalk/scripts/scarlet.js:46:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
```

**Comment by mrueger42** [comment]
you are missing the compile keyword on the command line on the second try.
Shouldn't crash like this though...

**Comment by HCHeidbrink** [comment]
Alexandre, you found a bug in the Scarlet build process. 
We will add your example and how to use it to the Readme.

For now, you can make your code compile by removing the explanation mark in 'Hello World!' using 
./scarlet compile /Users/alexandrebergel/Desktop/myapp.st

Compare your class definition with other definitions ins sclaret, though.

**Comment by bergel** [comment]
Yes, I got it to work. Indeed I missed the `compile` keyword. Sorry for that, was a rather obvious.
I can now compile my hello world. This has created a file `mobile.js`. I this this JavaScript file contains my hello world. But when I execute it using `node ~/Desktop/mobile.js`, then I see no print of `"hello world"`. 
I am probably missing something...

**Comment by johnmci** [comment]
So what interactive command are you giving to nodeJS?

....
John M. McIntosh. Corporate Smalltalk Consulting Ltd https://www.linkedin.com/in/smalltalk

**Comment by bergel** [comment]
I am not sure what you mean by `interactive command`. 
The whole process is the following:
1. I created the file `myapp.st` using the content: 
```Smalltalk
Object subclass: #MyApp
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MyApp'!

! MyApp class methodsFor: 'public' !
initialize
	Transcript show: 'Hello world!' ! !
```
1. I then compile it using `./scarlet compile /Users/alexandrebergel/Desktop/myapp.st`. It seems to compile well. 
```Smalltalk
➜  ScarletSmallTalk git:(master) ✗ ./scarlet compile /Users/alexandrebergel/Desktop/myapp.st
source: /Users/alexandrebergel/Desktop/myapp.st
/Users/alexandrebergel/Desktop/myapp.st
compile: /Users/alexandrebergel/Desktop/myapp.st
undefined
```
It prints `undefined`, although, not sure why.
1. I built it using `./scarlet build /Users/alexandrebergel/Desktop/`. 
```
➜  ScarletSmallTalk git:(master) ✗ ./scarlet build /Users/alexandrebergel/Desktop/
compile: /Users/alexandrebergel/Desktop/myapp.st
undefined
```
1. I try to run it using `node /Users/alexandrebergel/Desktop/mobile.js` but it does not print anything:
```
➜  ScarletSmallTalk git:(master) ✗ node  /Users/alexandrebergel/Desktop/mobile.js 
➜  ScarletSmallTalk git:(master) ✗ 
```

**Comment by johnmci** [comment]
Ok well I am on a train in the German countryside and not near my computer. However you need to run

./scarlet -i  mobile.js
> MyApp new

Which of course does self basicNew initialize

....
John M. McIntosh. Corporate Smalltalk Consulting Ltd https://www.linkedin.com/in/smalltalk

**Comment by bergel** [comment]
Weird... It does not work on my machine. It does:
```Smalltalk
➜  ScarletSmallTalk git:(master) ✗ ./scarlet -i /Users/alexandrebergel/Desktop/mobile.js
/Users/alexandrebergel/Desktop/mobile.js
> 
```

**Comment by johnmci** [comment]
Type
3+4 at the > prompt

....
John M. McIntosh. Corporate Smalltalk Consulting Ltd https://www.linkedin.com/in/smalltalk

**Comment by bergel** [comment]
Yes, that works well. But I cannot make `MyApp` print `hello world`.

**Comment by johnmci** [comment]
So if you type MyApp new what do you get,?

....
John M. McIntosh. Corporate Smalltalk Consulting Ltd https://www.linkedin.com/in/smalltalk

**Comment by bergel** [comment]
an error:
```
➜  ScarletSmallTalk git:(master) ✗ ./scarlet -i /Users/alexandrebergel/Desktop/mobile.js
/Users/alexandrebergel/Desktop/mobile.js
> MyApp new
Cannot read property '$$new' of undefined
> 
```

**Comment by johnmci** [comment]
Mmm
Smalltalk.MyApp().new()

....
John M. McIntosh. Corporate Smalltalk Consulting Ltd https://www.linkedin.com/in/smalltalk

**Comment by johnmci** [comment]
I think here maybe you need to check the contents of mobile.js and see if it contains the MyApp JavaScript source, maybe the result of the compile is not being appended to the JavaScript file. This not being loaded into nodeJS

....
John M. McIntosh. Corporate Smalltalk Consulting Ltd https://www.linkedin.com/in/smalltalk

**Comment by bergel** [comment]
I got this time:
```
➜  ScarletSmallTalk git:(master) ✗ ./scarlet -i /Users/alexandrebergel/Desktop/mobile.js
/Users/alexandrebergel/Desktop/mobile.js
> MyApp new
Cannot read property '$$new' of undefined
> Smalltalk.MyApp().new()
undefined
> 

```

**Comment by johnmci** [comment]
Ok see
If MyApp is in the JS file
....
John M. McIntosh. Corporate Smalltalk Consulting Ltd https://www.linkedin.com/in/smalltalk

**Comment by mrueger42** [comment]
on branch standalone there are a number of fixes (doIts with ! are now compiled and included) and additions (builds for mobile and standalone).
See the main README.md file and the ones in the examples directories.

**Comment by johnmci** [comment]
Fixed compiler to generate doIts. Added mobile and standalone builds
extended Readme with additional MyApp example usage.
Removed exclamation mark from 'Hello World!' to make code compile
Added thank you note to Alexandre Bergel

Still need to address exclamation mark issue

**Comment by mrueger42** [comment]
exclamation issue is fixed, that is the doIt part

**Comment by kurtkilpela** [comment]
In chunk format, exclamation marks need to be escaped. The string 'Hello, World!' would need to be written as 'Hello, World!!'.

Failure to escape the exclamation point will result in the chunk prematurely ending and the compiler to fail.

**Comment by PierceNg** [comment]
Hello. I played around and have it running on my web page. 

https://www.samadhiweb.com/blog/2019.12.21.scarlet.smalltalk.html
